import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export interface OfferLetterData {
  companyName: string;
  applicantName: string;
  positionTitle: string;
  salary: number | null;
  currency: string | null;
  startDate: string | null;
  benefits: string | null;
  terms: string | null;
  status: string;
  createdAt: string;
  respondedAt: string | null;
}

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a2e", lineHeight: 1.5 },
  header: { fontSize: 18, fontWeight: 700, marginBottom: 4 },
  date: { fontSize: 10, color: "#666", marginBottom: 24 },
  paragraph: { marginBottom: 12 },
  label: { fontWeight: 700 },
  section: { marginTop: 16, marginBottom: 8, fontSize: 12, fontWeight: 700 },
  footer: { marginTop: 32, fontSize: 9, color: "#777" },
});

function formatDate(d: string) {
  return new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export function OfferLetterTemplate({ data }: { data: OfferLetterData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>{data.companyName}</Text>
        <Text style={styles.date}>{formatDate(data.createdAt)}</Text>

        <Text style={styles.paragraph}>Dear {data.applicantName},</Text>
        <Text style={styles.paragraph}>
          We are pleased to offer you the position of <Text style={styles.label}>{data.positionTitle}</Text> at{" "}
          {data.companyName}. This letter outlines the key terms of our offer.
        </Text>

        <Text style={styles.section}>Position</Text>
        <Text style={styles.paragraph}>{data.positionTitle}</Text>

        {data.salary != null && (
          <>
            <Text style={styles.section}>Compensation</Text>
            <Text style={styles.paragraph}>
              {data.currency ?? "LKR"} {data.salary.toLocaleString()} per annum.
            </Text>
          </>
        )}

        {data.startDate && (
          <>
            <Text style={styles.section}>Start date</Text>
            <Text style={styles.paragraph}>{formatDate(data.startDate)}</Text>
          </>
        )}

        {data.benefits && (
          <>
            <Text style={styles.section}>Benefits</Text>
            <Text style={styles.paragraph}>{data.benefits}</Text>
          </>
        )}

        {data.terms && (
          <>
            <Text style={styles.section}>Additional terms</Text>
            <Text style={styles.paragraph}>{data.terms}</Text>
          </>
        )}

        <Text style={styles.paragraph}>
          We look forward to welcoming you to the team. Please review the details above and
          respond via the JobMo platform to accept or decline this offer.
        </Text>

        <View style={styles.footer}>
          <Text>
            Status: {data.status}
            {data.respondedAt ? ` — responded ${formatDate(data.respondedAt)}` : ""}
          </Text>
          <Text>Generated by JobMo — this document reflects the offer as recorded on the platform.</Text>
        </View>
      </Page>
    </Document>
  );
}
